include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
linter:
  rules:
    # Disable rules that conflict with very_good_analysis or are not needed
    public_member_api_docs: false
