name: blend_mask
description: A Flutter widget that applies BlendMode effects to its child widgets with proper layer compositing.
version: 1.0.0
homepage: https://github.com/CanArslanDev/blend_mask
repository: https://github.com/CanArslanDev/blend_mask
issue_tracker: https://github.com/CanArslanDev/blend_mask/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter: